language: node_js
node_js:
  - "node"
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
cache:
  directories:
    - "node_modules" # This will tell Travis CI to cache the dependencies
# script: npm test # Here you could also run the build step of your application
before_deploy: npm install now --no-save # Install Now CLI on Travis
deploy:
  - provider: script # Run a custom deployment script which we will define below
    script: now --build-env REACT_APP_DOMAIN=$NOW_URL --token $NOW_TOKEN
    skip_cleanup: true
    on:
      all_branches: true
      master: false
  - provider: script
    script: now --build-env REACT_APP_DOMAIN=$REACT_APP_DOMAIN --token $NOW_TOKEN && now alias jam-ci --token $NOW_TOKEN
    skip_cleanup: true
    on:
      master: true
